const gulprepUrl='github:my-cli/game-gulp-template',
    webpackrepUrl='github:my-cli/game-webpack-template',
    cmdNpm=process.platform==='win32'?'npm.cmd':'npm',
    tempDir=process.env[process.platform==='darwin'?'HOME':'USERPROFILE']+"\\.template",
    inquireQuests=[
        {
            type:'list',
            message:'请选择要使用的打包工具',
            name:'type',
            choices:[
                'gulp',
                'webpack'
            ]
        },
        {
            type:'input',
            message:'请输入媒体资源存放路径',
            name:'mediadir',
            default:'http://static.web.sdo.com/'
        },
        {
            type:'confirm',
            message:'是否安装项目依赖？',
            name:'isinstall'
        }
    ];
module.exports={gulprepUrl,webpackrepUrl,cmdNpm,inquireQuests,tempDir}